---
- hosts: all
  become: true

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3', 'python3-pip', 'python-pip', 'virtualenv', 'python3-setuptools', 'python-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: "{{ item }}"
      loop: [ 'docker' ]

    - name: Copy compose file
      template:
        src: docker-compose.j2
        dest: /tmp/docker-compose.yml
        owner: root
        group: root
        mode: '0644'
    
    - name: Log into DockerHub
      community.general.docker_login:
        username: "{{DOCKERHUB_USER}}"
        password: "{{DOCKERHUB_PASSWORD}}"

    - name: Init swarm
      community.general.docker_swarm:
        state: present

    - name: Deploy stack from a compose file
      shell:
        cmd: docker stack deploy --with-registry-auth --compose-file /tmp/docker-compose.yml final